### ISSUE TITLE
PB compound name

### ISSUE THREAD

**Issue by Fa10175** [vesta-webtrees-2-custom-modules/vesta_classic_laf#76] opened 2022-04-18 16:00 UTC
if you have a compound name like John-George Ernest and you put * behind John-George to indicate the common name you should see with webtrees 
![1](https://user-images.githubusercontent.com/10681601/163835974-1c1a44ed-60e8-4339-a04b-1a0f29d99d79.JPG)

validating the vesta module we have now

![2](https://user-images.githubusercontent.com/10681601/163836027-adf021d3-1e22-4463-a1fa-de7829ad1d04.JPG)

thanks

**Comment by ric2016** [comment] 2022-04-18 16:17
This is by design because there are individuals (both my parents are actually among them, that's mainly why I changed this ;-) ) with a compound name where the preferred name is only the last part of the compound name.

[See comment in code here.](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/blob/e35cc7fd28bd8183564a9bf2ac48b8e156000378/patchedWebtrees/IndividualExt.php#L181)

In Vesta, you can either use two asteriskes (bit ugly because the hyphen isn't underlined in that case, maybe I should change that), or unicode 2011 'Non-Breaking Hyphen' instead of a standard hyphen.

**Comment by Fa10175** [comment] 2022-04-18 16:27
but why webtrees have no problem ?

**Comment by Fa10175** [comment] 2022-04-18 16:34
It's no easy to find and replace unicode 2011 'Non-Breaking Hyphen' instead of a standard hyphen when you are more than 10000 name.
I thinks a lot of french people don't want to modify the gedcom

**Comment by ric2016** [comment] 2022-04-18 16:43
> It's no easy to find and replace

It's a single 'find-and-replace' operation, regardless of whether you have 10 or 10000 occurrences. (Of course you shouldn't do it manually)

But let me think about this a bit, I'll probably align with webtrees here and remove the Vesta adjustment.

**Comment by ric2016** [comment] 2022-04-18 19:49
Fixed in latest release (now works in the same way as in webtrees itself).

**Closed by ric2016** 2022-04-18 19:49 UTC

**Comment by Fa10175** [comment] 2022-04-19 10:00
Test Ok
Thanks
