### ISSUE TITLE
Find a special character broken in Firefox & Chrome

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_classic_laf#31] opened 2020-12-28 12:55 UTC
This issue is described in fisharebest/webtrees as
https://github.com/fisharebest/webtrees/issues/3635
![image](https://user-images.githubusercontent.com/350656/103215639-3c9c9380-4914-11eb-8965-19e623d94286.png)

It is caused by **Vesta Classic Look & Feel** enabled.
webtrees 2.0.10, vesta 2.0.10.3.0, 2.0.10.4.0

**Comment by ric2016** [comment] 2020-12-28 14:05
This is caused by using php DOMDocument for parsing and writing html (this is done to in order to strip header and footer from all edit dialogs, if 'compact layout' is selected).

DOMDocument doesn't handle HTML 5entities properly, see e.g. [here](https://stackoverflow.com/questions/43469435/phps-domdocument-appears-to-not-recognize-certain-html-entities-how-can-i-incl).
I'll use [HTML5DOMDocument](https://github.com/ivopetkov/html5-dom-document-php) instead.

Workaround until the next release is to disable the 'compact layout' option for edit dialogs.

**Comment by ric2016** [comment] 2021-01-01 11:32
Fixed in latest release.

**Closed by ric2016** 2021-01-01 11:32 UTC
