### ISSUE TITLE
Error in Vesta 2.1.2 for webtrees 2.1.2

### ISSUE THREAD

**Issue by Fa10175** [vesta-webtrees-2-custom-modules/vesta_classic_laf#79] opened 2022-05-06 14:47 UTC
if i go to  
Control panel
Manage family trees
Check for errors 
i selectionne one error example

```
Individual: [119I](http://localhost:8080/index.php?route=%2Ftree%2FF.ged%2Frecord%2F119I) — Line number: 11 — 3 TIME 04:00
Invalid GEDCOM tag. INDI:BIRT:DATE:TIME
```
 
i arrive to a display for this personne 
i try  to edit

then i save with no modification

i have this error 
`Fatal error: Uncaught RuntimeException: Output already started: <br /> <b>Warning</b>: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in <b>Unknown</b> on line <b>0</b><br /> in C:\...\webtrees\app\Http\Middleware\EmitResponse.php:112 Stack trace: #0 C:\...\webtrees\app\Http\Middleware\EmitResponse.php(67): Fisharebest\Webtrees\Http\Middleware\EmitResponse->assertBodyNotEmitted() #1 C:\...\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #2 C:\...\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #3 C:\...\webtrees\app\Webtrees.php(265): Middleland\Dispatcher->dispatch(Object(Nyholm in C:\...\htdocs\webtrees\app\Http\Middleware\EmitResponse.php on line 112`

if i disable  "Vesta Classic Look & Feel and" and  "Vesta Common" module,  it's work fine

thanks to find something

**Comment by ric2016** [comment] 2022-05-06 17:14
While I cannot reproduce this specific error, the main issue seems to be that we end up on a generic edit page.
[This is caused by webtrees not handling custom factories properly](https://github.com/fisharebest/webtrees/issues/4383).
Depending on how fast this gets fixed in webtrees, I may have to add a workaround in Vesta.

**Comment by ric2016** [comment] 2022-05-07 18:42
After further investigation, the underlying issue in webtrees for the actual error is [this one.](https://github.com/fisharebest/webtrees/issues/4389)

This usually doesn't occur as there normally is no edit dialog for an entire individual, and other facts and objects have a much smaller number of tags.

**Comment by ric2016** [comment] 2022-05-18 19:12
Handled in latest Vesta release (hopefully temporarily only, until webtrees fixes this).

**Closed by ric2016** 2022-05-18 19:12 UTC
